apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  # To avoid getting ourselves a bit stuck,
  # DO NOT auto sync ArgoCD.
  # We should confirm the app diff is correct before syncing
  syncPolicy: {}
  project: argocd
  source:
    repoURL: https://github.com/dzungda/argocd-testing.git
    path: argocd-install/argo-cd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - ../values-override.yaml
      version: v3
