apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: azure-ci-east-asia
  destination:
    name: in-cluster
    namespace: argocd

  # To avoid getting ourselves a bit stuck,
  # DO NOT auto sync ArgoCD.
  # We should confirm the app diff is correct before syncing
  syncPolicy: {}

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 3.17.5
    helm:
      values: |
        installCRDs: true

        # applicationSet:
        #   enabled: false

        global:
          image:
            tag: "v2.1.1"

        server:
          service:
            type: LoadBalancer

          additionalApplications:
            - name: ci-argo-cd
              namespace: argocd
              project: default
              destination:
                name: in-cluster
                namespace: argocd
              syncPolicy:
                automated:
                  selfHeal: true
              source:
                repoURL: https://github.com/dzungda/argocd-testing.git
                targetRevision: HEAD
                path: managed/
                directory:
                  recurse: true
        
          
