apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guesbook
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: azure-ci-east-asia
  source:
    path: guestbook/
    repoURL: https://github.com/dzungda/argocd-testing.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
