apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: azure-ci-east-asia
  destination:
    name: in-cluster
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 40.5.0
    helm:
      values: |
        alertmanager:
          service:
            type: LoadBalancer

        prometheus:
          service:
            type: LoadBalancer
